definitions:
  config:
    /hippo:configuration/hippo:modules/web-archiving-addon-services-daemon/hippo:moduleconfig/archivemanager:
      className:
        operation: override
        type: string
        value: org.bloomreach.forge.webarchiving.archivemanagers.archiefweb.ArchiefWebArchiveManager
      archiefweb.api.username: 'REPLACE_WITH_USERNAME'
      archiefweb.api.password: 'REPLACE_WITH_PASSWORD'
      archiefweb.api.endpoint.auth: '/od_login.php'
      archiefweb.api.endpoint.request: '/protected.php'


