definitions:
  config:
    /hippo:configuration/hippo:modules/crispregistry/hippo:moduleconfig/crisp:resourceresolvercontainer/archiefWebEndpoint:
      jcr:primaryType: crisp:resourceresolver
      crisp:beandefinition: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<beans\
        \ xmlns=\"http://www.springframework.org/schema/beans\"\r\n       xmlns:xsi=\"\
        http://www.w3.org/2001/XMLSchema-instance\"\r\n       xsi:schemaLocation=\"\
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd\"\
        >\r\n \r\n  <bean parent=\"abstractCrispSimpleJacksonRestTemplateResourceResolver\"\
        \r\n        class=\"org.onehippo.cms7.crisp.core.resource.jackson.SimpleJacksonRestTemplateResourceResolver\"\
        >\r\n    <property name=\"cacheEnabled\" value=\"false\" />\r\n    <property\
        \ name=\"baseUri\" value=\"${archiefweb.api.base.uri}\" />\r\n \
        \   <property name=\"restTemplate\">\r\n      <bean class=\"org.springframework.web.client.RestTemplate\"\
        >\r\n        <property name=\"requestFactory\" ref=\"org.springframework.http.client.ClientHttpRequestFactory\"\
        \ />\r\n      </bean>\r\n    </property>\r\n  </bean>\r\n</beans>"
      crisp:propnames: [archiefweb.api.base.uri]
      crisp:propvalues: ['https://ondemandsp1.archiefweb.eu/api']
