definitions:
  config:
    /hippo:configuration/hippo:modules/web-archiving-addon-services-daemon/hippo:moduleconfig/archivemanager:
      className:
        value: org.bloomreach.forge.webarchiving.archivemanagers.tester.TesterWebArchiveManager
      tester.sleep.seconds: '3'
